//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "cex_bot_sell_order")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub bot_id: i64,
    pub ty: i32,
    pub symbol: String,
    pub client_order_id: String,
    pub order_id: u64,
    pub status: i32,
    pub price: String,
    pub quantity: String,
    pub real_price: Option<String>,
    pub real_quantity: Option<String>,
    pub real_quote_qty: Option<String>,
    pub quote_fee: Option<String>,
    pub cancel_order_id: Option<u64>,
    pub cancel_order_status: Option<i32>,
    pub buy_order_ids: Json,
    pub profit: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
