//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub mod prelude;

pub mod cex_binance_kline_csv;
pub mod cex_bot;
pub mod cex_bot_asset;
pub mod cex_bot_order;
pub mod cex_bot_position;
pub mod cex_bot_sell_order;
pub mod cex_market;
pub mod cex_market_symbol;
