refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%+)(utc)} [{f}:{L}] {h({l})} {M}:{m}{n}"
    filters:
      - kind: threshold
        level: info
  file:
    kind: rolling_file
    path: "logs/request.log"
    encoder:
      pattern: "[{d(%Y-%m-%dT%H:%M:%S%.6f)} {h({l}):<5.5} {M}] {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 2 gb
      roller:
        kind: fixed_window
        pattern: "logs/old-rolling_file-{}.log"
        base: 0
        count: 2

root:
  level: info
  appenders:
    - stdout
    - file